#!/usr/bin/env bash

USAGE=$(cat <<EOF
$(basename $0) [ -v | --verbose ] [ --gui ] [ --ini INIFILE ]  OUTPUT MODEL [ MODEL [ ... ] ]
EOF
)

while [[ "$1" != "" ]]; do
   case "$1" in
       "--help" | "-h")
         echo "$USAGE"
         exit 0
         ;;
       "--ini")
         INIFILE=$1
         ;; 
       "--gui")
         PREVIEW=yes
         ;;
       "-v" | "--verbose")
         set -x
         ;;
       *)
         if [[ $1 =~ ^- ]]
         then
             echo "Unrecognized option $1"
             echo $USAGE
             exit 1
         fi
         
         if [[ -z $OUTPUT ]]
         then
             OUTPUT=$1
         else
           MODELS="$MODELS $1"
         fi
         ;;
   esac
   shift
done

if [[ -z $OUTPUT ]]
then
    echo "OUTPUT is required"
    echo $USAGE
    exit 1
fi

if [[ -z $MODELS ]]
then
    echo "At least one model is required"
    echo $USAGE
    exit 1
fi

if [[ -z $INIFILE ]]
then
    INIFILE=$OUTPUT.ini
fi

TIMESTAMP=$(date +'%Y%m%d-%H%M%S')

echo "Building STL files..."
STLS=$(for MODEL in $MODELS; do echo $MODEL.generated.stl; done)

make $STLS

if [[ ! -e $INIFILE ]]
then
    echo "${INIFILE} does not exist. Creating an empty file."
    touch ${INIFILE}
else
  echo "Using $INIFILE"
fi

mkdir -p config

echo "Building gcode"
slic3r --load ../config/makergear-m2.ini \
       --load ../config/abs.ini \
       --load ${INIFILE} \
       --save config/${OUTPUT}_${TIMESTAMP}.ini \
       --notes "generated_at_${TIMESTAMP}" \
       --merge $STLS \
       --output ${OUTPUT}_${TIMESTAMP}.gcode


if [[ -n $PREVIEW ]]
then
    slic3r --gui --load config/${OUTPUT}_${TIMESTAMP}.ini --merge ${STLS}
fi

